error: remove failing code from microb integration
In commit 51836e1 the code responsible
for microb integration was removed, but not completely. Those remainings
caused benchmark to exit with non-zero exit code if strict mode is on,
which is true by default on any Debug build of Tarantool